# Habilitar a interface web do H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurar a URL e credenciais do banco em memória
spring.datasource.url=jdbc:h2:mem:musicdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Pedir para o JPA/Hibernate criar as tabelas automaticamente baseadas nas nossas Entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect